// Generated by scripts/generate-contracts.mjs. Do not edit.
export const RunStatus = ["QUEUED","RUNNING","WAITING","PAUSING","PAUSED","CANCELLING","SUCCEEDED","FAILED","CANCELLED"] as const;
export type RunStatus = typeof RunStatus[number];
export const StepStatus = ["BLOCKED","READY","RUNNING","WAITING","SUCCEEDED","FAILED","CANCELLED","SKIPPED"] as const;
export type StepStatus = typeof StepStatus[number];
export const AttemptStatus = ["CLAIMED","RUNNING","SUCCEEDED","FAILED","TIMED_OUT","LOST","CANCELLED"] as const;
export type AttemptStatus = typeof AttemptStatus[number];
export const ApprovalStatus = ["PENDING","APPROVED","REJECTED","EXPIRED","CANCELLED"] as const;
export type ApprovalStatus = typeof ApprovalStatus[number];
export const TimerStatus = ["PENDING","FIRED","CANCELLED"] as const;
export type TimerStatus = typeof TimerStatus[number];
export const WorkerStatus = ["ONLINE","DRAINING","OFFLINE","REVOKED"] as const;
export type WorkerStatus = typeof WorkerStatus[number];
export const RecoveryMode = ["safe","idempotent","reconcile"] as const;
export type RecoveryMode = typeof RecoveryMode[number];
