// Code generated by scripts/generate-contracts.mjs; DO NOT EDIT.
package contracts

type RunStatus string

const (
	RunStatusQUEUED     RunStatus = "QUEUED"
	RunStatusRUNNING    RunStatus = "RUNNING"
	RunStatusWAITING    RunStatus = "WAITING"
	RunStatusPAUSING    RunStatus = "PAUSING"
	RunStatusPAUSED     RunStatus = "PAUSED"
	RunStatusCANCELLING RunStatus = "CANCELLING"
	RunStatusSUCCEEDED  RunStatus = "SUCCEEDED"
	RunStatusFAILED     RunStatus = "FAILED"
	RunStatusCANCELLED  RunStatus = "CANCELLED"
)

type StepStatus string

const (
	StepStatusBLOCKED   StepStatus = "BLOCKED"
	StepStatusREADY     StepStatus = "READY"
	StepStatusRUNNING   StepStatus = "RUNNING"
	StepStatusWAITING   StepStatus = "WAITING"
	StepStatusSUCCEEDED StepStatus = "SUCCEEDED"
	StepStatusFAILED    StepStatus = "FAILED"
	StepStatusCANCELLED StepStatus = "CANCELLED"
	StepStatusSKIPPED   StepStatus = "SKIPPED"
)

type AttemptStatus string

const (
	AttemptStatusCLAIMED   AttemptStatus = "CLAIMED"
	AttemptStatusRUNNING   AttemptStatus = "RUNNING"
	AttemptStatusSUCCEEDED AttemptStatus = "SUCCEEDED"
	AttemptStatusFAILED    AttemptStatus = "FAILED"
	AttemptStatusTIMED_OUT AttemptStatus = "TIMED_OUT"
	AttemptStatusLOST      AttemptStatus = "LOST"
	AttemptStatusCANCELLED AttemptStatus = "CANCELLED"
)

type ApprovalStatus string

const (
	ApprovalStatusPENDING   ApprovalStatus = "PENDING"
	ApprovalStatusAPPROVED  ApprovalStatus = "APPROVED"
	ApprovalStatusREJECTED  ApprovalStatus = "REJECTED"
	ApprovalStatusEXPIRED   ApprovalStatus = "EXPIRED"
	ApprovalStatusCANCELLED ApprovalStatus = "CANCELLED"
)

type TimerStatus string

const (
	TimerStatusPENDING   TimerStatus = "PENDING"
	TimerStatusFIRED     TimerStatus = "FIRED"
	TimerStatusCANCELLED TimerStatus = "CANCELLED"
)

type WorkerStatus string

const (
	WorkerStatusONLINE   WorkerStatus = "ONLINE"
	WorkerStatusDRAINING WorkerStatus = "DRAINING"
	WorkerStatusOFFLINE  WorkerStatus = "OFFLINE"
	WorkerStatusREVOKED  WorkerStatus = "REVOKED"
)

type RecoveryMode string

const (
	RecoveryModesafe       RecoveryMode = "safe"
	RecoveryModeidempotent RecoveryMode = "idempotent"
	RecoveryModereconcile  RecoveryMode = "reconcile"
)
